version: '3.8'

services:
  front:
    build:
      context: ./rate_my_repo
    ports:
      - "5173:5173"
    depends_on:
      - back
    networks:
      - app-network
    command: npm run dev -- --host

  back:
    build:
      context: ./Back
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./Back:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpass
      - DB_NAME=rate_my_repo

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=rate_my_repo
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Back/config/rate_my_repo.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
